# This file is auto-generated by openmediavault (https://www.openmediavault.org)
# WARNING: Do not edit this file, your changes will get lost.

# Enable bash completion in interactive shells.
# Added by openmediavault.
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi
PS1="\[\e[37m\][\[\e[36m\]\u\e[31m\]@\[\e[33m\]@\h \[\e[32m\]\W\[\e[0m\]]\\$ "
